import '../styles/globals.css';
import React, { ReactNode } from 'react';
import { AppProps } from 'next/dist/next-server/lib/router/router';
import '@fontsource/roboto';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps): ReactNode {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
    </>;
}

export default MyApp;
